name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.7
          - 3.0
          - 3.1
          - 3.2
          - 3.3
    name: Tests Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@dffc446db9ba5a0c4446edb5bca1c5c473a806c5 # v1.235.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: latest
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get -y install libsqlite3-dev
      - name: Run tests
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec rake
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@dffc446db9ba5a0c4446edb5bca1c5c473a806c5 # v1.235.0
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get -y install libsqlite3-dev
      - name: Run style checks
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
